name: Build, Test, and Archive Xcode Project for iPhone

on:
  push:
    branches: [ main ] # Remplace par ta branche principale si nécessaire

jobs:
  build_test_archive:
    runs-on: macos-latest
    steps:
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in the project directory
        run: ls -la

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app
        
      - name: List Schemes
        run: xcodebuild -project Nikolai.xcodeproj -list

      - name: Build for iPhone
        run: |
          xcodebuild \
            -project Nikolai.xcodeproj \
            -scheme Nikolai \
            -destination 'generic/platform=iOS Simulator' \
            clean build

      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project Nikolai.xcodeproj \
            -scheme Nikolai \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            test

      - name: Run UI Tests
        run: |
          xcodebuild \
            -project Nikolai.xcodeproj \
            -scheme Nikolai \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            test

      - name: Archive and Export .ipa
        run: |
          # Archive le projet
          xcodebuild \
            -project Nikolai.xcodeproj \
            -scheme Nikolai \
            -configuration Release \
            -archivePath $PWD/build/MyApp.xcarchive \
            archive

          # Exporte l'.ipa
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/MyApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build \
            -allowProvisioningUpdates

      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp.ipa
          path: build/MyApp.ipa
